services:
  mongo:
    image: mongo:8.0.32
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--quiet', '--eval', 'db.adminCommand("ping").ok']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mongo-data:
